### ISSUE TITLE
ELB creation fails for tasks that do not include a container named "web"

### ISSUE THREAD

**Issue by kylerippey** [tongueroo/ufo#114]
Hello 👋 

I just started investigating this project and I like the look of it so far, but I have encountered one issue when trying to run `ufo deploy --elb=true` for a service that does not include a `web` container.

I'm trying to deploy a Fargate service with a container named `api` like so:
```
deply ship --elb=true
```
During deployment, it encounters the following error and a rollback is triggered:
```
CREATE_FAILED AWS::ECS::Service Ecs The container web does not exist in the task definition. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ...)
```

In the CFN stack generated on AWS I see a `web` container referenced in the LoadBalancer config, which in my case should be `api`:
```
Resources:
  Ecs:
    Type: AWS::ECS::Service
    Properties:
      ...
      LoadBalancers:
        Fn::If:
        - CreateTargetGroupIsTrue
        - - ContainerName: web    # incorrect, should be api
            ContainerPort: 80
            TargetGroupArn:
              Ref: TargetGroup
        - Fn::If:
          - ElbTargetGroupIsBlank
          - []
          - - ContainerName: web    # incorrect, should be api
              ContainerPort: 80
              TargetGroupArn:
                Ref: ElbTargetGroup
      ...
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ...
      ContainerDefinitions:
      - Name: api                   # correct
```

I believe the problem is caused by the following lines being hardcoded, but I'm not sure if the dynamic container name is available in this template: https://github.com/tongueroo/ufo/blob/389d2f02370ff6556c7420fb4e775a39c6915884/lib/ufo/stack/builder/resources/ecs.rb#L35 https://github.com/tongueroo/ufo/blob/389d2f02370ff6556c7420fb4e775a39c6915884/lib/ufo/stack/builder/resources/ecs.rb#L46
